#!/usr/bin/env python

"""This tags new cargo program versions automatically with a vX.X.X-git tag"""
from subprocess import run, check_call, DEVNULL, CalledProcessError
import toml

def check_cargo_toml_version():
    with open("Cargo.toml") as cargo_toml_file:
        parsed = toml.loads(cargo_toml_file.read())
        try:
            version: str = parsed["package"]["version"]
            return version
        except KeyError:
            return None

print('Checking for version updates...')

new_version = check_cargo_toml_version()

run(['git', 'stash'], stdout=DEVNULL, stderr=DEVNULL)
run(['git', 'checkout', 'HEAD~1'], stdout=DEVNULL, stderr=DEVNULL)
old_version = check_cargo_toml_version()

run(['git', 'checkout', '-'], stdout=DEVNULL, stderr=DEVNULL)
run(['git', 'stash', 'pop'], stdout=DEVNULL, stderr=DEVNULL)
if new_version == old_version:
    print(f"New version found: {new_version}")
    try:
        check_call(['git', 'tag', '-a', f'v{new_version}', '-m', '""'], stdout=DEVNULL, stderr=DEVNULL)
        print("Added tag!")
    except CalledProcessError as c:
        print(f"Failed to add tag. {c}")
else:
    print('No new version found')
